"""
Item 4 follow-up -- full-resolution EmotiBit clock-sync analysis.

Newly available: a timeSyncMap.csv AND a timesyncs.csv (continuous log of
individual NTP-style sync pings, roughly every 5s throughout the WHOLE
session, with round-trip latency per ping) now exist for all 79 valid
sessions, regenerated by the user via the EmotiBit app. This supersedes the
2-point timeSyncMap.csv calibration used earlier (audit_synchronization_
evidence.py's item (a), n=1) with a robust, full-session, per-ping fit.

timesyncs.csv columns: RD, TS_received, TS_sent, AK, RoundTrip
  RD, TS_received, AK : EmotiBit onboard millisecond-counter readings
  TS_sent             : local/reference wall-clock time the ping was sent,
                         format YYYY-MM-DD_HH-MM-SS-microseconds, local
                         (Riyadh, UTC+3)
  RoundTrip           : round-trip latency (ms)

Latency-compensated reference time per ping: TS_sent_unix + RoundTrip/2/1000
(confirmed empirically against timeSyncMap.csv's own TL0/TE0 anchor values).

For every session this:
  1. Fits robust_time_unix = a + b * TS_received_ms via linear regression
     over ALL sync pings, after dropping outlier-latency pings (>3x median
     RoundTrip) that would bias the reference-time estimate.
  2. Reports the fitted drift rate (ppm) and fit quality (max residual).
  3. Compares the fitted absolute-time anchor against the CURRENTLY-RELEASED
     anchor (filename-parsed, whole-second resolution) to quantify exactly
     how much each session's EmotiBit-to-VBOX alignment would shift if the
     release were regenerated with this calibration.
  4. Flags any session where the sync-ping fit itself looks unreliable
     (poor linearity, large gaps, non-monotonic pings) -- evidence of a
     mid-session WiFi/clock issue.

Usage:
    python audit_emotibit_timesync_full.py

Environment variables:
    STAGING_DATA_ROOT   raw per-driver session folders (containing EmotiBit/)
"""
from __future__ import annotations

import os
import re
from datetime import datetime, timezone, timedelta
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
TRIM_CSV = REPO_ROOT / "04_session_trimming" / "trim_review_output" / "trim_points_final.csv"
STAGING_DATA_ROOT = Path(os.environ.get("STAGING_DATA_ROOT", ""))

import sys
sys.path.insert(0, str(REPO_ROOT / "02_dataset_construction"))
import emotibit_sync as es  # noqa: E402 -- reuse its SKIP_TAGS/SAMPLE_RATES exactly


def find_raw_ts_start(main_csv: Path) -> float | None:
    """
    Reproduces emotibit_sync.py's _load_raw_csv() ts_start logic exactly: the
    device-clock timestamp (ms) of the first row whose tag is valid (has a
    known sample rate) and not in SKIP_TAGS. This is the actual EmotiBitTs_0
    zero-point the release's per-row unix_time = t_start_unix +
    (EmotiBitTs - EmotiBitTs_0)/1000 formula uses -- NOT 0, and NOT any
    particular sync ping's own device-time reading.
    """
    with open(main_csv, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            parts = line.rstrip("\n").split(",")
            if len(parts) < 4:
                continue
            try:
                ts_ms = float(parts[0])
                tag = parts[3].strip()
            except ValueError:
                continue
            if tag in es.SKIP_TAGS or tag not in es.SAMPLE_RATES:
                continue
            return ts_ms
    return None

OUT_DIR = Path(__file__).resolve().parent / "validation_output"
OUT_DIR.mkdir(exist_ok=True)

UTC_OFFSET_HOURS = 3
TS_SENT_RE = re.compile(r"(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})-(\d+)")


def load_sessions() -> pd.DataFrame:
    df = pd.read_csv(TRIM_CSV)
    return df[df["status"] == "ok"][["tag", "driver", "session"]]


def find_emotibit_dir(driver: int, session: int) -> Path | None:
    for sname in (f"Session {session}", f"Session_{session}", f"Session{session}", f"Seesion {session}"):
        d = STAGING_DATA_ROOT / f"D{driver}" / sname / "EmotiBit"
        if d.exists():
            return d
    return None


def ts_sent_to_unix(s: str) -> float | None:
    m = TS_SENT_RE.match(s.strip())
    if not m:
        return None
    yr, mo, dy, hh, mi, ss, us = (int(x) for x in m.groups())
    us = int(str(us).ljust(6, "0")[:6])  # normalise to microseconds
    dt = datetime(yr, mo, dy, hh, mi, ss, us, tzinfo=timezone(timedelta(hours=UTC_OFFSET_HOURS)))
    return dt.timestamp()


import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "02_dataset_construction" / "regen_v2"))
from timesync_calibration import fit_calibration  # noqa: E402  -- shared with the regeneration pipeline


def parse_filename_anchor(main_csv_name: str) -> float | None:
    """Reproduces the CURRENT (whole-second-only) released anchor logic."""
    m = re.match(r"(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})", main_csv_name)
    if not m:
        return None
    yr, mo, dy, hh, mi, ss = (int(x) for x in m.groups())
    dt = datetime(yr, mo, dy, hh, mi, ss, tzinfo=timezone(timedelta(hours=UTC_OFFSET_HOURS)))
    return dt.timestamp()


def analyse_session(tag: str, driver: int, session: int) -> dict | None:
    emb_dir = find_emotibit_dir(driver, session)
    if emb_dir is None:
        return {"tag": tag, "status": "NO_DIR"}

    # Choose the real (largest) main recording first, then pair with THAT file's
    # own timesyncs log by filename stem. Sessions with a brief aborted
    # recording attempt (D1_S1, D3_S2, D4_S1, D16_S3) also carry a second,
    # near-empty timesyncs log; an unordered glob() previously picked it for
    # 3 of those 4 sessions, giving spurious TOO_FEW_PINGS / absurd drift
    # rows. This mirrors the pairing used by regen_v2/emotibit_sync_v2.py.
    main_csvs = sorted(
        [f for f in emb_dir.glob("*.csv")
         if re.match(r"\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}", f.name) and "_" not in f.stem[19:20]],
        key=lambda f: f.stat().st_size, reverse=True)
    if not main_csvs:
        return {"tag": tag, "status": "NO_MAIN_CSV"}
    paired = emb_dir / f"{main_csvs[0].stem}_timesyncs.csv"
    sync_files = [paired] if paired.exists() else []
    if not sync_files:
        return {"tag": tag, "status": "NO_TIMESYNCS_CSV"}

    ts = pd.read_csv(sync_files[0], header=0,
                      names=["RD", "TS_received", "TS_sent", "AK", "RoundTrip", "_blank"],
                      dtype={"TS_sent": str})
    ts = ts.dropna(subset=["TS_received", "TS_sent", "RoundTrip"])
    ts["ref_unix"] = ts["TS_sent"].apply(ts_sent_to_unix) + ts["RoundTrip"].astype(float) / 2000.0
    ts = ts.dropna(subset=["ref_unix"])
    if len(ts) < 5:
        return {"tag": tag, "status": "TOO_FEW_PINGS", "n_pings": len(ts)}

    median_rt = ts["RoundTrip"].median()
    clean = ts[ts["RoundTrip"] <= max(3 * median_rt, median_rt + 20)]
    n_dropped_outliers = len(ts) - len(clean)

    x_ms = clean["TS_received"].to_numpy(dtype=float)
    y_unix = clean["ref_unix"].to_numpy(dtype=float)

    # Mean-centre before fitting: raw unix timestamps (~1.75e9) combined with
    # ms-scale device counters (~1e6) in a degree-1 polyfit lose sub-ms
    # precision to float64 catastrophic cancellation (unix time already
    # consumes ~10 of float64's ~16 significant decimal digits). Fit on
    # offsets from the first sample instead.
    x0, y0 = x_ms[0], y_unix[0]
    x = (x_ms - x0) / 1000.0   # seconds, device clock
    y = y_unix - y0            # seconds, reference clock, relative to y0

    # Iterative robust fit: a minority of pings show large (up to ~1s), isolated
    # residual jumps with otherwise-normal round-trip latency (confirmed on
    # D4_S3 -- not round-trip noise, some other source, e.g. a discrete
    # reference-clock correction event), which a plain least-squares fit lets
    # dominate the slope estimate. Refit after excluding points >5 MAD from
    # the previous fit's residuals, twice.
    keep = np.ones(len(x), dtype=bool)
    for _ in range(3):
        slope, intercept = np.polyfit(x[keep], y[keep], 1)
        resid_all = y - (slope * x + intercept)
        mad = np.median(np.abs(resid_all[keep] - np.median(resid_all[keep]))) or 1e-6
        new_keep = np.abs(resid_all - np.median(resid_all[keep])) <= 5 * 1.4826 * mad
        if new_keep.sum() == keep.sum():
            keep = new_keep
            break
        keep = new_keep
    n_robust_outliers = int((~keep).sum())
    pred = slope * x + intercept
    resid = y - pred
    max_resid_ms = float(np.max(np.abs(resid[keep])) * 1000) if keep.any() else float(np.max(np.abs(resid)) * 1000)
    ppm_drift = (slope - 1.0) * 1e6

    span_s = x.max() - x.min()
    # Previous (pre-fix) anchor: filename-parsed, whole-second only, from the
    # same main_csvs[0] chosen above
    released_anchor = parse_filename_anchor(main_csvs[0].name)
    raw_ts_start = find_raw_ts_start(main_csvs[0])

    # New, calibrated anchor: fitted reference time at the first (cleaned) sync
    # ping's device time (x=0 by construction of the offset fit above), i.e.
    # y0 + intercept. Compared against what the RELEASE'S OWN FORMULA predicts
    # at that same device-time point: unix_t = released_anchor +
    # (x_ms[0] - raw_ts_start)/1000 (raw_ts_start = EmotiBitTs_0, the actual
    # first-sample device timestamp used by _load_raw_csv -- NOT 0, and NOT
    # the sync ping's own device-time reading, which was the earlier bug).
    calibrated_at_first_ping = float(y0 + intercept)
    released_at_first_ping = (
        released_anchor + (x_ms[0] - raw_ts_start) / 1000.0
        if released_anchor is not None and raw_ts_start is not None else None
    )
    shift_s = (calibrated_at_first_ping - released_at_first_ping) if released_at_first_ping is not None else None

    # Anchor-only model (release default since 2026-09-09): slope fixed at 1,
    # session-median offset; the largest sustained offset step in the log is
    # the per-session bound on residual cross-device alignment error. Computed
    # with the same shared code the regeneration pipeline uses.
    cal_ao = fit_calibration(sync_files[0], model="anchor_only")
    ao_at_first_ping = float(cal_ao.y0_unix + cal_ao.intercept) if cal_ao is not None else None
    ao_shift_s = ((ao_at_first_ping - released_at_first_ping)
                  if (ao_at_first_ping is not None and released_at_first_ping is not None) else None)

    return {
        "tag": tag, "status": "ok", "n_pings": len(ts), "n_pings_used": len(clean),
        "n_dropped_outliers": n_dropped_outliers, "n_robust_outliers": n_robust_outliers,
        "span_s": span_s, "ppm_drift": ppm_drift, "max_fit_residual_ms": max_resid_ms,
        "released_anchor_unix": released_anchor, "calibrated_anchor_shift_s": shift_s,
        "anchor_only_shift_s": ao_shift_s,
        "anchor_only_max_step_s": cal_ao.max_step_s if cal_ao is not None else None,
        "anchor_only_step_at_s": cal_ao.step_at_s if cal_ao is not None else None,
        "anchor_only_max_resid_ms": cal_ao.max_resid_ms if cal_ao is not None else None,
        "anchor_only_mad_ms": cal_ao.mad_ms if cal_ao is not None else None,
    }


def main():
    if not STAGING_DATA_ROOT.exists():
        raise SystemExit(f"STAGING_DATA_ROOT not found or unset: {STAGING_DATA_ROOT!r}")

    sessions = load_sessions()
    rows = [analyse_session(r["tag"], int(r["driver"]), int(r["session"])) for _, r in sessions.iterrows()]
    df = pd.DataFrame(rows)
    df.to_csv(OUT_DIR / "emotibit_timesync_full_report.csv", index=False)

    print(f"Sessions checked: {len(df)}")
    print(df["status"].value_counts().to_string())

    ok = df[df["status"] == "ok"]
    print(f"\n=== Sessions with a usable timesyncs.csv fit: {len(ok)} / {len(df)} ===")
    if not ok.empty:
        print(f"Sync pings per session: median {ok['n_pings'].median():.0f}, "
              f"range {ok['n_pings'].min()}-{ok['n_pings'].max()}")
        print(f"Calibration span: median {ok['span_s'].median()/60:.1f} min "
              f"(vs. earlier n=1 estimate of 14.9 min)")
        print(f"\nDrift rate (ppm) across all {len(ok)} sessions:")
        print(f"  mean={ok['ppm_drift'].mean():.1f}  median={ok['ppm_drift'].median():.1f}  "
              f"std={ok['ppm_drift'].std():.1f}  min={ok['ppm_drift'].min():.1f}  max={ok['ppm_drift'].max():.1f}")
        print(f"\nFit quality (max residual from linear fit, ms):")
        print(f"  median={ok['max_fit_residual_ms'].median():.2f}  "
              f"max={ok['max_fit_residual_ms'].max():.2f}  "
              f"(sessions with >50ms max residual: {(ok['max_fit_residual_ms']>50).sum()})")

        shifts = ok.dropna(subset=["calibrated_anchor_shift_s"])
        print(f"\n=== Shift between CURRENTLY-RELEASED anchor and full-calibration anchor "
              f"({len(shifts)} sessions) ===")
        print(f"  mean={shifts['calibrated_anchor_shift_s'].mean():.3f}s  "
              f"median={shifts['calibrated_anchor_shift_s'].median():.3f}s  "
              f"std={shifts['calibrated_anchor_shift_s'].std():.3f}s")
        print(f"  min={shifts['calibrated_anchor_shift_s'].min():.3f}s  "
              f"max={shifts['calibrated_anchor_shift_s'].max():.3f}s")
        print(f"  |shift| > 0.5s: {(shifts['calibrated_anchor_shift_s'].abs()>0.5).sum()} sessions")
        print(f"  |shift| > 1.0s: {(shifts['calibrated_anchor_shift_s'].abs()>1.0).sum()} sessions")
        print(f"  |shift| > 2.0s: {(shifts['calibrated_anchor_shift_s'].abs()>2.0).sum()} sessions")
        print("\nTop 10 largest |shift| sessions:")
        top = shifts.reindex(shifts["calibrated_anchor_shift_s"].abs().sort_values(ascending=False).index).head(10)
        print(top[["tag", "calibrated_anchor_shift_s", "ppm_drift", "n_pings_used", "span_s"]].to_string(index=False))

    bad = df[~df["status"].isin(["ok"])]
    if not bad.empty:
        print(f"\n=== Sessions with a problem ({len(bad)}) ===")
        print(bad.to_string(index=False))

    print(f"\nFull report: {OUT_DIR / 'emotibit_timesync_full_report.csv'}")


if __name__ == "__main__":
    main()
